#!/bin/bash
for (( ; ; ))
    do
        BATTINFO=`acpi -b`
        if [[ `echo $BATTINFO | grep Discharging` && `echo $BATTINFO | cut -f 5 -d " "` < 01:30:00 ]] ; then
            DISPLAY=:0.0 /usr/bin/notify-send "low battery" "$BATTINFO"
        fi
        #if [[ `echo $BATTINFO | grep Charging` && `echo $BATTINFO | cut -f 5 -d " "` > 10:00:00 ]] ; then
        #    DISPLAY=:0.0 /usr/bin/notify-send "Charged" 
        #fi
        sleep 60
    done
